sudo: required
language: go
go: 1.9.x

addons:
  apt:
    packages:
      - redis-server
# Disallowing packages: ipvsadm
# If you require these packages, please review the package approval process at: https://github.com/travis-ci/apt-package-whitelist#package-approval-process

services: redis-server
before_install:
  - go get github.com/kardianos/govendor

install:
  - govendor sync
script: go test -v ./...
