sudo: required
language: go
go: 1.6

addons:
  apt:
    packages:
      - redis-server
# Disallowing packages: ipvsadm
# If you require these packages, please review the package approval process at: https://github.com/travis-ci/apt-package-whitelist#package-approval-process

services: redis-server
install: go get -t -v .
script: go test -v ./...
